version: 2
jobs:
  build:
    working_directory: ~/repo/frontend
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: get-yarn
          command: "sudo npm install -g yarn@1.9.4"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: run-test
          command: yarn test
